[PB-534]: feature/Show the list of folders you have shared with other users
internxt/sdk pull request #150
Opened 2023-07-11 07:11 UTC by CandelR

- Added functions to fetch private shared folders

2023-08-09 07:48 UTC, sg-gs requested changes

2023-08-09 07:48 UTC, sg-gs commented on src/drive/share/index.ts
> +    userEmail,
Shouldn't this be the user uuid instead of the email?
https://github.com/internxt/drive-server-wip/blob/2c3541146e56ae548d1d799f712c514331f63346/src/modules/private-share-folder/dto/update-private-sharing-folder-role.dto.ts#L6

2023-08-09 07:48 UTC, sg-gs commented on src/drive/share/types.ts
> +  owner_id: string;
Even if this field exists, as we use camelCase, I would just ignore it

2023-08-09 09:05 UTC, CandelR commented on src/drive/share/index.ts
> +    userEmail,
Good catch! I had drive-server-wip on local out of date and I forgot to change it.

2023-08-09 11:49 UTC, sg-gs approved these changes
Some of the paths are prone to change @CandelR

2023-08-09 11:49 UTC, sg-gs commented on src/drive/share/types.ts
> +  shared_with: string;
Same here with the camel case

2023-08-09 13:37 UTC, CandelR commented
> Some of the paths are prone to change @CandelR

What do you mean, that can change the paths of the enpdoints? Anyway, we will have to add the others as they are developed, we can change them later. We need this released for the staging environment.

2023-08-10 08:48 UTC, sg-gs approved these changes

2023-08-10 08:49 UTC, sg-gs commented
> > Some of the paths are prone to change @CandelR
> 
> What do you mean, that can change the paths of the enpdoints? Anyway, we will have to add the others as they are developed, we can change them later. We need this released for the staging environment.

Yeah, that's why I just left the comment but approved the PR, it was just a FYI.

2023-08-10 09:28 UTC, merged